name: macOS-CI
on: [push, pull_request]

jobs:
  build:
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
    runs-on: macOS-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          brew install libjpeg-turbo libpng
          if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
            brew install gcc@9
          fi
      - name: Build string_theory
        run: |
          mkdir -p build_deps && cd build_deps
          if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
            export CC=gcc-9
            export CXX=g++-9
          fi
          git clone https://github.com/zrax/string_theory
          mkdir -p string_theory/build && cd string_theory/build
          cmake -DCMAKE_BUILD_TYPE=Debug -DST_BUILD_TESTS=OFF \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/build_deps/prefix" ..
          make -j2 && make install
      - name: Build libhsplasma
        run: |
          mkdir build && cd build
          if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
            export CC=gcc-9
            export CXX=g++-9
          fi
          mkdir install
          cmake -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/build_deps/prefix;/usr/local/opt/jpeg-turbo;/usr/local/opt/openssl" \
            -DCMAKE_INSTALL_PREFIX=install \
            -DENABLE_PYTHON=ON -DENABLE_TOOLS=ON -DENABLE_NET=ON -DENABLE_PHYSX=OFF ..
          make -j2 && make install
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: libhsplasma-${{matrix.compiler}}-${{github.sha}}
          path: build/install
